import { createEmptyRichTextValue } from '../utils/richText.jsx'
import { GENERIC_TEMPLATE_ID } from './templates'

export const createInitialCard = () => ({
  templateId: GENERIC_TEMPLATE_ID,
  name: createEmptyRichTextValue('left'),
  traits: createEmptyRichTextValue('center'),
  actionIcon: 'A',
  actionCustom: createEmptyRichTextValue('right'),
  school: 'Evocation',
  description: createEmptyRichTextValue('left'),
  frontArtworkText: createEmptyRichTextValue('left'),
  details: '',
  image: '',
  frontArtworkLayout: 'art-only',
  frontArtworkBackgroundMode: 'transparent',
  frontArtworkBackgroundColor: '#ffffff',
  frontArtworkBorderThickness: 1,
  frontArtworkBorderColor: '#444444',
  cardFrameCurve: 10,
  frontArtworkFrameCurve: 6,
  imageBack: '',
  frontBackgroundImage: '',
  borderThickness: 1,
  borderColor: '#333333',
  descriptionBoxColor: '#ffffff',
  descriptionBoxOpacity: 0.82,
  frontBackgroundMode: 'solid',
  frontBackgroundGradientType: 'linear',
  frontBackgroundColor: '#feffff',
  frontBackgroundSecondaryColor: '#dce4f0',
  backBackgroundMode: 'solid',
  backBackgroundGradientType: 'linear',
  backBackgroundColor: '#feffff',
  backBackgroundSecondaryColor: '#dce4f0',
})
