import { createEmptyRichTextValue } from '../utils/richText.jsx'

export const createInitialCard = () => ({
  name: createEmptyRichTextValue(),
  traits: createEmptyRichTextValue(),
  actionIcon: 'A',
  actionCustom: createEmptyRichTextValue(),
  school: 'Evocation',
  description: createEmptyRichTextValue(),
  details: '',
  image: '',
  imageBack: '',
  frontBackgroundImage: '',
  borderThickness: 1,
  borderColor: '#333333',
  descriptionBoxColor: '#ffffff',
  descriptionBoxOpacity: 0.82,
  frontBackgroundMode: 'solid',
  frontBackgroundGradientType: 'linear',
  frontBackgroundColor: '#feffff',
  frontBackgroundSecondaryColor: '#dce4f0',
  backBackgroundMode: 'solid',
  backBackgroundGradientType: 'linear',
  backBackgroundColor: '#feffff',
  backBackgroundSecondaryColor: '#dce4f0',
})
